"""Initial

Revision ID: 74ef14d837a7
Revises: 
Create Date: 2025-10-26 14:39:16.972035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '74ef14d837a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacturers',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='check_manufacturer_unique_name')
    )
    op.create_index(op.f('ix_manufacturers_name'), 'manufacturers', ['name'], unique=False)
    op.create_table('cars',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=11, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('price >= 0', name='check_price_positive'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cars_color'), 'cars', ['color'], unique=False)
    op.create_index(op.f('ix_cars_name'), 'cars', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cars_name'), table_name='cars')
    op.drop_index(op.f('ix_cars_color'), table_name='cars')
    op.drop_table('cars')
    op.drop_index(op.f('ix_manufacturers_name'), table_name='manufacturers')
    op.drop_table('manufacturers')
    # ### end Alembic commands ###
